### ISSUE TITLE
zsyncmake2 could be less verbose or support a --quiet (or --verbose)

### ISSUE THREAD

**Issue by lalten** [AppImageCommunity/zsync2#74]
zsyncmake2 prints its version to stderr on every invocation.
It also supports `--version` so I think this is a little too noisy.
You can `2>/dev/null` of course but you will miss any real warnings/errors messages.

**Comment by probonopd** [comment]
Thanks @lalten. The assumption is that this gets run in CI systems often where it is useful to see the version in the log file, so I think this works as designed.

**Comment by lalten** [comment]
Actually my use case is a CI system and that's why its important to me that logs are clean so important errors can be seen and there is no noise distracting from what's important
